language: csharp
os: windows
solution: DeveloperBox.sln

jobs:
  include: 
    - dotnet: 4.7.2
    - mono: latest
branches:
  only:
  - master

notifications:
  email: false
  # email:
    # on_failure: always # default: always

install:
  - nuget restore DeveloperBox.sln 
  - nuget install Costura.Fody -Version 4.1.0 #-OutputDirectory libs
  - nuget install Newtonsoft.Json -Version 12.0.3 #-OutputDirectory libs
  - nuget install ZXing.Net -Version  0.16.5 #-OutputDirectory libs

script:
  - msbuild /p:Configuration=Release DeveloperBox.sln

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file:
    - ./DeveloperBox/bin/Release/DeveloperBox.exe
  skin_cleanup: true
  on:     # 发布时机           
    tags: true       # tags 设置为 true 表示只有在有 tag 的情况下才部署
    branches:
      only:
        master
